### ISSUE TITLE
expense(支出)テーブルを作成する

### ISSUE THREAD

**Issue by YushiroDodo63** [NUTFes/FinanSu#472]
# 開発目的

expense(支出)テーブルを作成する。
予算ページで支出用の表を表示する必要があり、そこで使用するために支出テーブルを作成する。
支出テーブルは、購入報告されたものの合計金額と、その支出がどこからか(情報局, 本部運営費)を管理するためのものである。

# 考えられる開発内容

expenseテーブルを作成し、purchaseReport テーブルに `expenseID` のカラムを追加する。
expenseテーブルのカラムは以下の通りとする。
`id: int , name: string,  totalPrice(合計金額): int , items(項目): array, yearID: int`
totalPrice に関しては、紐づく購入報告（purchaseReport）で `financeCheck` が `true` の合計金額が入る。
items に関しては、expense に紐づく購入報告に紐づく購入された物品を１〜３個(仮なので何個でもOK. 個数指定が難しければ全部でOK) 取得して配列に格納する。

# 考えられる開発時間

# 備考

**Comment by imaimai17468** [comment]
一回間違えてマージしているためcloseされてしまっていた
rebaseしたためreopen
